# Generated by Django 5.0.2 on 2024-03-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crea', '0026_propiedad_disponible_observaciones_procesos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='area',
            field=models.CharField(choices=[('Aprovicionamiento', 'Aprovicionamiento'), ('Ventas', 'Ventas'), ('Tramites', 'Tramites'), ('Gerencia', 'Gerencia')], max_length=50, null=True),
        ),
    ]
