# Generated by Django 5.0.2 on 2024-03-10 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crea', '0027_alter_empleado_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='caracteristica',
            field=models.CharField(choices=[('Vendido', 'Vendido'), ('En Seguimiento', 'En Seguimiento'), ('Descartado', 'Descartado')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad_disponible',
            name='proceso',
            field=models.CharField(choices=[('Contado', 'Contado'), ('Credito', 'Credito')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propiedad_disponible',
            name='proceso_venta',
            field=models.CharField(choices=[('1', 'Levantamiento planimétrico de compra y venta (1 semana)'), ('2', 'Aprobación de la planimetría en el municipio (3 semanas)'), ('3', 'Minuta y documentación en notaria (4 días)'), ('4', 'Ingreso de la carpeta en notaria (3 días)'), ('5', 'Espera para la asignación de un perito evaluador (3 semanas)'), ('6', 'Aprobación de perito evaluador (3 días)'), ('7', 'Crédito aprobado'), ('8', 'Firmas de traspaso de dominio en notaria'), ('9', 'Registro del crédito hipotecario en el municipio(3 días)'), ('10', 'Fin')], max_length=60, null=True),
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_procesocliente', to='Crea.cliente')),
                ('id_empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_procesoempleado', to='Crea.empleado')),
                ('id_propiedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_procesopropiedad', to='Crea.propiedad_disponible')),
            ],
        ),
    ]
